"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 24;
let altura = 1.90;
const nacionalidade = 'brasileira';
const colegas = ['Douglas', 'Gabriela'];
const tecnologias = ['html', 'css'];
const notas = [7, 9, 10];
const lista = ['Douglas', true, 24];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
